### PR TITLE
Update free-programming-books-it.md

### PR DESCRIPTION
**Pull request by lucatwiv**
Popular free java book

### CODE REVIEW

**Comment by vhf** [comment]
I'm not convinced this book is free. Could you provide me with some kind of proof?

Thanks

**Comment by lucatwiv** [comment]
You can open the link e download it. It's a popular free book in Italy, although was released in 2001.

**Comment by vhf** [comment]
Is the book explicitly stating that it is free?

**Comment by lucatwiv** [comment]
absolutely free, but it's outdated, now i think it's better to reject the pull request.

**Pull request closed without merging**
