### PR TITLE
Handmade Hero

### PR DESCRIPTION
**Pull request by chan18**
is an free online video course for creating professional-quality game by Casey Muratori(https://mollyrocket.com/casey/about.html)

### CODE REVIEW

**Comment by vhf** [comment]
Thanks! Is this a course or a screencast?

**Comment by chan18** [comment]
nightly live broadcast, he streams on twitch, course/screencast!

**Comment by chan18** [comment]
can we have video game development section, i know some bunch of free video game screen cast free written tutorials/websites competitive game development tutorials(ludamdare) ?

**Comment by vhf** [comment]
Sure, a video game dev section would be nice.

Is this link to a book, a course or a screencast ?

**Comment by chan18** [comment]
https://hero.handmade.network/episodes ---> handmade hero is a screencast because i am pointing to archive of videos he did on live-stream(twitch) .  But tutorialspoint.com is a website of course written for easy to read and understand for all level of people, But you can download them all for free as pdf .

**Pull request closed without merging**
