### PR TITLE
Added two python books

### PR DESCRIPTION
**Pull request by quake004**
I suggest writing down what books are open source so people seeking to translate a book can find one quickly.

### CODE REVIEW

**Comment by vhf** [comment]
I think it's not worth the effort.

**Comment by eshellman** [comment]
I have also thought about doing this; I would help out if we could get agreement on how to go about it. Perhaps the best way to approach it is to create an issue.

**Comment by diggydoc4u** [comment]
I.think creating a issue is the best way to really test this.

**Comment by borgified** [comment]
going to have to put it in alphabetical order later. thx for your contribution!

**Pull request merged**
