### PR TITLE
Updated R Books

### PR DESCRIPTION
**Pull request by navdeep-G**

### CODE REVIEW

**Comment by vhf** [comment]
Hmmm, the linter still fails, sorry about that. I cannot fix it right now (nor can I review your PR but it looks good!), please keep this PR open until tomorrow.

**Comment by navdeep-G** [comment]
Sure. No problem!

**Comment by vhf** [comment]
Hey, I finally found time to review your PR. I'm not convinced these books are free. I'll reopen if someone provides a proof that these are indeed free.

**Comment by navdeep-G** [comment]
Could you explain why you think that is? Maybe I can do some research to find out. This website was recommended to me, but maybe they were mistaken somehow.

**Comment by vhf** [comment]
These books being hosted on some website does not mean they are being legally distributed.

Take a look at the copyright notice of the first book. It does not say you can freely redistribute it.

**Comment by navdeep-G** [comment]
Ah. Terribly sorry about that. I will look for that next time. I guess I was a bit to hasty in trying to get books to the open source.

Thanks!

**Pull request closed without merging**
