### PR TITLE
Add Linux Inside of @0xAX

### PR DESCRIPTION
**Pull request by joelhandwell**
Linux Inside is a series of posts about the linux kernel and its insides.

### CODE REVIEW

**Comment by joelhandwell** [comment]
@vhf Is there anything more can be done for this to be merged?

**Comment by eshellman** [comment]
The book is a great fit. I wish that @0xAX wouldn't be so modest in the description. "A series of posts" makes it sound like a blog!

**Comment by vhf** [comment]
Sorry about the delay, many thanks @joelhandwell :+1:

**Comment by joelhandwell** [comment]
Many thanks to the author 0xAX

**Pull request merged**
