### PR TITLE
Added Python Books 'Think Complexity & 'How to Make Mistakes in Python' ,8 more Python Courses and 1 more Python Problem Set Site

### PR DESCRIPTION
**Pull request by SentinelWarren**
Added two new python books

### CODE REVIEW

**Comment by SentinelWarren** [comment]
Added some more contents

**Comment by vhf** [comment]
Thanks! Could you please rebase your commits?

**Comment by SentinelWarren** [comment]
@vhf i keep on messing up when i try to rebase,an help please?

**Comment by vhf** [comment]
I'll take care of it.

**Comment by vhf** [comment]
Merged here abf27a88bb8edd5c4941b77270cc91c2b21a56b6

**Comment by SentinelWarren** [comment]
help please! it doesn't work!

**Pull request closed without merging**
