### PR TITLE
Added The C Programming Language, 2nd Edition (PDF)

### PR DESCRIPTION
**Pull request by efeelaiho**
Added The C Programming Language, 2nd Edition by Brian Kernighan and Dennis Ritchie.
It's a pdf file of the entire book, free to download.

### CODE REVIEW

**Comment by vhf** [comment]
This book isn't free.

**Comment by pickfire** [comment]
How come? I thought it is free since it's so old. There are tons of link http://freecomputerbooks.com/The-C-Programming-Language.html

**Comment by vhf** [comment]
Old does not mean free.

**Comment by snailfastrun** [comment]
hello,my English is poor ,what is mean?

At 2017-03-05 19:07:00, "Ivan Tham" <notifications@github.com> wrote:


How come? I thought it is free since it's so old. There are tons of link http://freecomputerbooks.com/The-C-Programming-Language.html

**Comment by eshellman** [comment]
I corresponded with Kernighan about this book. It's not free.

**Pull request closed without merging**
