### PR TITLE
Replace dead SO link with archived one

### PR DESCRIPTION
**Pull request by onebree**
Found this dead link still on the README

### CODE REVIEW

**Comment by onebree** [comment]
@vhf The reSRC project is no longer active, but still present on the README. I wanted to link to the repo, but could not find any material that would be helpful, besides tests and assets. What should we do in this case?

**Comment by vhf** [comment]
Regarding reSRC, feel free to remove any reference to it from the README and add these commits to this PR, I'll merge it. :)

Thanks a lot!

**Comment by onebree** [comment]
@vhf made the second commit :-)

Besides web archive, can we still access material from resrc.io? I couldn't find anything upon a quick browse of the repo

**Comment by vhf** [comment]
Unfortunately not...

**Pull request merged**
