### PR TITLE
Added Hadoop 'Succinctly' titles

### PR DESCRIPTION
**Pull request by sixeyed**
Three Syncfusion ebooks on Hadoop & ecosystem
- Disclaimer - all by me.

### CODE REVIEW

**Comment by sixeyed** [comment]
Second commit replacing all other Syncfusion book links with the friendly 'details' page - rather than the register page.

**Comment by kataras** [comment]
@sixeyed Could you, please, check the alphabetical ordering and put two blank lines between last section and next heading?

**Comment by sixeyed** [comment]
@kataras  - done, sorry for missing that.

**Comment by kataras** [comment]
Don't be sorry, no worries, I'm not an official repository's  maintainer, I just saw that and wanted to give a small help :)

**Pull request closed without merging**
