### PR TITLE
Criado o tópico de expressões regulares e adicionado o livro "Expressões regulares - Guia de consulta rápida"

### PR DESCRIPTION
**Pull request by evertonl1ma**

### CODE REVIEW

**Comment by onebree** [comment]
Can this be translated to English, then denoted whether the source itself is Spanish..?

**Comment by evertonl1ma** [comment]
The source is pt- BR.

**Comment by onebree** [comment]
Please excuse my ignorance. At first glance, it looked closest to Spanish for me.

**Comment by evertonl1ma** [comment]
No problem. :)
They are not difficult to confundidadas , and I think I just left confused when not specify the language it was .

**Pull request closed without merging**
