### PR TITLE
added link to book  Art of Programming Contest

### PR DESCRIPTION
**Pull request by AkashChandrakar**

### CODE REVIEW

**Comment by vhf** [comment]
Is this link really a book?

**Comment by AkashChandrakar** [comment]
yeah this link corresponds to author website of the book.This website contains a link to the book.

**Comment by vhf** [comment]
I took another look and still couldn't find the book. Could you please give me a direct link to it or help me find it?

**Comment by AkashChandrakar** [comment]
Here is the link http://www.comp.nus.edu.sg/~stevenha/database/Art_of_Programming_Contest_SE_for_uva.pdf

**Comment by vhf** [comment]
I'm sorry but I still cannot find the book on the link you provide in this PR.

I went there 3 times now and couldn't find this PDF. I suspect most readers of this repo will not be able to find it either.

**Pull request closed without merging**
