### PR TITLE
(~20%) Update broken links from url_checker

### LINKED ISSUE #1586: HELP_WANTED: update broken URLs
been a while since i checked our links so this is a big one. feel free to create pull requests to fix the problems shown below. you may also want to manually test the link in case it was temporarily down at the time of testing.

free-programming-interactive-tutorials-en.md
404 Not Found http://jhusain.github.io/learnrx/

free-programming-books-ja.md
500 Can't connect to www.narihiro.info:80 (Connection refused) http://www.narihiro.info/g1gc-impl-book/
404 Not Found http://rd.clojure-users.org/
500 Can't connect to www.doyouphp.jp:80 (Bad hostname) http://www.doyouphp.jp/book/book_phpdp.shtml
404 Not Found http://www4.ocn.ne.jp/~inukai/scheme_primer_j.html
404 Not Found http://karetta.jp/book-cover/gauche-hacks
404 Not Found http://gst.plasticheart.info/tutorial-c84

free-programming-books-gr.md

free-programming-books-tr.md
500 Internal Server Error http://www.kaanaslan.com/resource/course_note/download_file.php?file_id=16

free-programming-books-hu.md

free-programming-books.md
404 Not Found http://stackoverflow.com/revisions/392926/175
404 Not Found http://www.songho.ca/opengl/index.html):
404 Not Found http://see.stanford.edu/see/materials/aimlcs229/handouts.aspx
404 Not Found http://web.mit.edu/~holden1/www/math/number-theory.pdf
404 Not Found http://www.iitg.ac.in/kartha/CE601-14/CourseSchedule.htm),2014
404 Not Found http://cm.bell-labs.com/cm/ms/what/shannonday/paper.html
404 Not Found http://public.dhe.ibm.com/common/ssi/ecm/en/ram14011usen/RAM14011USEN.PDF
404 Not Found http://ftacademy.org/materials/fsm/11
403 Forbidden http://www.cs.jhu.edu/~scott/pl/book/dist/
500 Can't connect to www.advancedlinuxprogramming.com:80 (Connection refused) http://www.advancedlinuxprogramming.com/
500 Service unavailable (with message) http://www.heatonresearch.com/articles/series/20
404 Not Found http://www.cs.uwm.edu/~cs654/handouts/cool-manual.pdf
403 Forbidden http://media.developerforce.com/workbooks/HerokuPostgres_Workbooks_Web_Final.pdf
500 Can't connect to gradle.org:443 (certificate verify failed) http://www.gradleware.com/registered-access?content=books%2Fbuilding-and-testing%2F
404 OK http://spock-framework.readthedocs.org/en/latest/
404 Not Found http://www.astro.virginia.edu/class/oconnell/astr511/IDLresources/getting-started-IDL-v7.0.pdf
404 Not Found http://www.astro.virginia.edu/class/oconnell/astr511/IDLresources/IDLguide.html
404 Not Found http://www.rogerstokes.free-online.co.uk/book.htm
500 Service unavailable (with message) http://www.heatonresearch.com/articles/series/3
404 Not Found https://leanpub.com/hibernate4-example-programs
500 Service unavailable (with message) http://www.heatonresearch.com/articles/series/16
500 Service unavailable (with message) http://www.heatonresearch.com/articles/series/1
500 Service unavailable (with message) http://www.heatonresearch.com/articles/series/15
404 Not Found http://wicket.apache.org/guide/
404 Not Found http://jqfundamentals.com/book/
500 Can't connect to www.advancedlinuxprogramming.com:80 (Connection refused) http://www.advancedlinuxprogramming.com/
500 read timeout http://ocamlunix.forge.ocamlcore.org/
500 Can't connect to www.csupomona.edu:443 https://www.csupomona.edu/~jrfisher/www/prolog_tutorial/pt_framer.html
404 Not Found http://beastie.cs.ua.edu/cs150/book/index.html
500 Can't connect to readruby.io:80 (Bad hostname) http://readruby.io/
500 Can't connect to modular.math.washington.edu:80 (timeout) http://modular.math.washington.edu/books/sagebook/sagebook.pdf

javascript-frameworks-resources.md
404 Not Found http://dl.e-book-free.com/2013/07/knockoutjs_starter.pdf

free-programming-books-ru.md
404 Not Found http://www.soslan.ru/tcp/
400 Bad Request https://dl.dropboxusercontent.com/u/4606839/%D0
404 Not Found http://ru.wikibooks.org/wiki/%D0
404 Not Found http://ru.wikibooks.org/wiki/%D0
404 Not Found http://ru.wikibooks.org/wiki/%D0
404 Not Found http://ru.wikibooks.org/wiki/%D0

free-programming-books-pt_PT.md

free-programming-books-id.md
404 Not Found http://kristories.gitbooks.io/mongodb-untuk-indonesia/

free-programming-books-pt_BR.md
404 Not Found http://herberthamaral.com/posts/2013-02-25-sobre-o-jquery-fundamentals.html

free-programming-books-de.md
404 Not Found http://www.iaik.tugraz.at/content/teaching/bachelor_courses/betriebssysteme/downloads/schmaranz2.pdf

free-programming-books-sk.md

free-programming-books-se.md

free-programming-books-fr.md
404 Not Found http://framabook.org/histoires-et-cultures-du-libre/
404 Not Found http://framabook.org/option-libre-du-bon-usage-des-licences-libres/
404 Not Found http://framabook.org/8-produire-du-logiciel-libre/

free-programming-books-zh.md
500 Can't connect to www.coursera.org:443 https://www.coursera.org/courses?orderby=upcoming&lngs=zh
404 Not Found http://ocw.mit.edu/courses/translated-courses/simplified-chinese/
404 Not Found http://island205.github.io/tlboc/
404 Not Found https://www.gitbook.com/book/0532/nodejs/details)%EF
404 Not Found http://wusuopu.gitbooks.io/symfony2_tutorial/content
500 Can't connect to r6rs.mrliu.org:443 http://r6rs.mrliu.org/)%EF

free-programming-books-ro.md

free-programming-books-it.md

free-programming-books-az.md

free-programming-books-cs.md

free-courses-en.md

free-programming-books-es.md
404 Not Found http://docencia.izt.uam.mx/pece/pagina_academica/AA/indexa.html
404 Not Found http://www.aliatuniversidades.com.mx/bibliotecasdigitales/pdf/sistemas/Analisis_y_disenio_de_algoritmos.pdf
500 Can't connect to www.cursosdeprogramacionadistancia.com:80 (Bad hostname) http://www.cursosdeprogramacionadistancia.com/static/pdf/material-sin-personalizar-agile.pdf
404 Not Found http://savannah.nongnu.org/hg/?group=elisp-es
500 Can't connect to gitimmersion.mx:80 (Bad hostname) http://gitimmersion.mx
500 Can't connect to library.originalhacker.org:80 (Bad hostname) http://library.originalhacker.org/biblioteca/articulo/ver/123
500 Can't connect to www.cursosdeprogramacionadistancia.com:80 (Bad hostname) http://www.cursosdeprogramacionadistancia.com/static/pdf/material-sin-personalizar-php.pdf
500 Can't connect to flanagan.ugr.es:80 (timeout) http://flanagan.ugr.es/perl/index2.htm
500 Can't connect to www.cursosdeprogramacionadistancia.com:80 (Bad hostname) http://www.cursosdeprogramacionadistancia.com/static/pdf/material-sin-personalizar-python.pdf

free-programming-books-bg.md

free-programming-books-ua.md

free-programming-books-pl.md

free-programming-books-fa_IR.md
500 Can't connect to laravel.ir:80 (Bad hostname) http://laravel.ir/

free-programming-books-ko.md

### PR DESCRIPTION
**Pull request by onebree**
~20% of links found in #1586 (url_checker). THIS WILL NOT CLOSE THE ENTIRE ISSUE.

- free-programming-interactive-tutorials-en.md
  + [x] 404 Not Found http://jhusain.github.io/learnrx/
- free-programming-books-ja.md
  + [x] 500 Can't connect to www.narihiro.info:80 (Connection refused) http://www.narihiro.info/g1gc-impl-book/
  + [x] 404 Not Found http://rd.clojure-users.org/
  + [x] **ARCHIVED** > 500 Can't connect to www.doyouphp.jp:80 (Bad hostname) http://www.doyouphp.jp/book/book_phpdp.shtml
  + [x] **ARCHIVED** > 404 Not Found http://www4.ocn.ne.jp/~inukai/scheme_primer_j.html
  + [x] **ARCHIVED** > 404 Not Found http://karetta.jp/book-cover/gauche-hacks
  + [x] 404 Not Found http://gst.plasticheart.info/tutorial-c84
- free-programming-books-tr.md
  + [x] ~~500 Internal Server Error http://www.kaanaslan.com/resource/course_note/download_file.php?file_id=16~~
- free-programming-books.md
  + [ ] 404 Not Found http://stackoverflow.com/revisions/392926/175
  + [x] ~~404 Not Found http://www.songho.ca/opengl/index.html~~
  + [x] 404 Not Found http://see.stanford.edu/see/materials/aimlcs229/handouts.aspx
  + [x] 404 Not Found http://web.mit.edu/~holden1/www/math/number-theory.pdf
  + [x] 404 Not Found http://www.iitg.ac.in/kartha/CE601-14/CourseSchedule.htm),2014
  + [x] 404 Not Found http://cm.bell-labs.com/cm/ms/what/shannonday/paper.html

### CODE REVIEW

**Comment by onebree** [comment]
- Some links are crossed out because they worked for me (New Jersey, USA). If they do not work elsewhere, let me know.
- Some Japanese links are unchecked. Because I do not know Japanese, I used the Web Archive links for the meantime
- The "original list" from StackOverflow can no longer be found, not even on Web Archive

**Comment by onebree** [comment]
Note to self: squash commits 5adb785, 51ea4bc, d836607 as they all update free courses doc

**Comment by fredericksilva** [comment]
👍🏻

**Comment by onebree** [comment]
@borgified This pull request is ready for review. I made it smaller so others could submit changes, as well.

**Comment by borgified** [comment]
:+1:

**Comment by fredericksilva** [comment]
:+1:

**Pull request merged**
