### PR TITLE
Added a new link in pt_BR books - A semana PHP

### PR DESCRIPTION
**Pull request by leonardorifeli**
Added a new link in pt_BR books - A semana PHP

### CODE REVIEW

**Comment by vhf** [comment]
Thanks! Please don't remove blank lines and add your links alphabetically.

**Comment by leonardorifeli** [comment]
Hello! I'm sorry. I corrected this.

**Comment by vhf** [comment]
No problem, I'll fix the blank lines after merging. Could you please rebase your work on top of master? Your fork seems to be ~60 commits behind the current master.

**Comment by leonardorifeli** [comment]
I corrected the blank line. Oh, ok. I will rebase my fork. Thanks.

**Comment by leonardorifeli** [comment]
I'm sorry, but, I could not compare my fork because the Github can’t automatically merge.

**Comment by vhf** [comment]
You could add my repo as a remote and rebase your commits on top of it,
manually solving the conflicts.

**Comment by leonardorifeli** [comment]
Thanks. I compare my fork and updated.

**Comment by vhf** [comment]
bfbd7a3b9610e15d93f1e810d95d3ca7d2e0c306 is messing up the commit history. Not sure if this would help, but could you squash your commits? If it does not help, I'll add these two books for you.

**Comment by leonardorifeli** [comment]
Oh, I think it does not help. Do you can add two books for me?

**Pull request merged**
