### PR TITLE
Introduction to Rx

### PR DESCRIPTION
**Pull request by asd-and-Rizzo**

### CODE REVIEW

**Comment by vhf** [comment]
Great, thanks @asd-and-Rizzo! Please:

* Remove the trailing slash
* Insert this entry in alphabetical order

**Comment by asd-and-Rizzo** [comment]
Seems work for script here.

**Comment by vhf** [comment]
What do you have in mind @asd-and-Rizzo ?

**Comment by switchhax** [comment]
Is the trailing slash the last `/`?

**Pull request closed without merging**
