### PR TITLE
Arabic free programming books list

### PR DESCRIPTION
**Pull request by hamidos**

### CODE REVIEW

**Comment by vhf** [comment]
Nice, thanks for your interest in this project!

**Comment by hamidos** [comment]
Yes I will.

**Comment by bpinsky** [comment]
Please remove me

**Comment by hamidos** [comment]
From what ?

**Comment by bpinsky** [comment]
I am getting alot of emails from the group i dont want i tried to
unsubscribe on git but it doesnt work. Something I am missing likely. I
figured someone here could help

**Comment by vhf** [comment]
@bpinsky Log into your github account and click "unwatch" on the top of [this page](https://github.com/vhf/free-programming-books), or use the links on the bottom of your email notifications while logged in.

**Comment by bpinsky** [comment]
Thanks!

**Comment by bpinsky** [comment]
I set itto ignoring on th

**Comment by eshellman** [comment]
These are all good resources, but since the PR was submitted, another arabic page was created and accepted. Would really appreciate it if you could merge the pages.

**Pull request closed without merging**
