### PR TITLE
Added three great R books

### PR DESCRIPTION
**Pull request by Dripdrop12**

### CODE REVIEW

**Comment by eshellman** [comment]
1. not clear that R Graphics Cookbook is free: http://www.cookbook-r.com/Graphs/
2. "R for Data Science" and "The caret Package" are great additions.
3. Alphabetize the entries. g after f and d before s.

**Comment by Dripdrop12** [comment]
What about books like those on leanpub.com that can be $0?  Are those free?

**Comment by eshellman** [comment]
read the travis report - need to remove trailing slashes.

There are lots of Leanpub books on here. Sometimes, though, the intent of the authors is to use the $0 minimum as a temporary promotional price which is hard to track.

**Comment by vhf** [comment]
Thanks!

**Pull request merged**
