### PR TITLE
Use relative path

### PR DESCRIPTION
**Pull request by timkrueger**
Use relative paths for internal links

### CODE REVIEW

**Comment by timkrueger** [comment]
Sorry. But I don't get what I've done wrong.

**Comment by switchhax** [comment]
Well this time, Travis talks some inconclusive stuff (sadly ...). Ehm, i would try to remove the trailing slash.

**Comment by vhf** [comment]
Travis job just crashed, no big deal, I reran the job and it's all good.

I may be missing the point of this PR though, is there a good reason to use a relative link here?

**Comment by timkrueger** [comment]
@vhf Sure in my view ;-). 

If you [fork](https://github.com/timkrueger/free-programming-books) or [mirror](https://code.timkrueger.me/tim/free-programming-books) the repository, you have also a link to **your** fork or mirror.

**Pull request merged**
