### PR TITLE
Fix links to "A Guide to Python's Magic Methods" and "Probability and Statistics Cookbook"

### PR DESCRIPTION
**Pull request by garrmark**

### CODE REVIEW

**Comment by vhf** [comment]
Thanks for your PR. A big incoming PR fixing these two links being already in the pipeline, I think it will be easier to close this one without merging it as soon as the other lands. Sorry about that. :(

**Comment by garrmark** [comment]
No worries, last I looked the new links in the other PR were different.  Once that one is in, I'll check again and close or modify if I feel these links are better.

**Comment by vhf** [comment]
Great, thank you! The other PR has just been merged, please check and report. :)

**Comment by garrmark** [comment]
The magic method link is still broken, I'll close this PR and open a new one with that change

**Pull request closed without merging**
