### PR TITLE
Update problem-sets-competitive-programming.md

### PR DESCRIPTION
**Pull request by switchhax**
I´m a bit inactive, bu anyways, here´s a PR :D

### CODE REVIEW

**Comment by vhf** [comment]
Thanks!

Please include the protocol for rosalind.

**Comment by switchhax** [comment]
What protocol do you mean?

**Comment by vhf** [comment]
`http` or `https`

**Comment by switchhax** [comment]
Well i can do this, but the browser "swallows it ..."

**Comment by vhf** [comment]
Thanks!

**Pull request merged**
