### PR TITLE
Update free-programming-books.md

### PR DESCRIPTION
**Pull request by glauberfc**
Add a new ebook: Pratical ES6

### CODE REVIEW

**Comment by glauberfc** [comment]
Will to be this commit accepted?

**Comment by tedyoung** [comment]
@glauberfc - you'll have to be patient and wait for @vhf to get to it. It looks good to me, though.

**Comment by vhf** [comment]
I wasn't able to access this book's content. Is it really free?

**Comment by glauberfc** [comment]
@vhf you only need to do a single tweet for unlock all content.

**Comment by vhf** [comment]
Weird. When I tried a few minutes ago it asked to access my twitter account.

**Pull request closed without merging**
