### PR TITLE
Updating pt_PT and pt_BR

### PR DESCRIPTION
**Pull request by henriquev16**
In both files interactive-tutorials-pt_pt or pt_br, Link redirects to a closed YouTube account, files deleted.
Added a book to pt_PT

### CODE REVIEW

**Comment by henriquev16** [comment]
Why this was not updated yet?

**Comment by vhf** [comment]
Because it requires a manual merge. Could you squash your commits and make sure there's no conflict?

**Comment by henriquev16** [comment]
I don't understand the problem, can you please explain me what I can do to solve it?

Thanks

**Comment by onebree** [comment]
@henriquev16 Did you make your commits on your local machine, or on the Github website? If you are not familiar with command-line git, I can open a pull request for you with zero conflicts

**Comment by henriquev16** [comment]
Hi, I did it on the GitHub website. Although I have a few knowledge of command-line git I appreciate if you can open a zero conflicts pull request !

Thank you !

**Comment by onebree** [comment]
@henriquev16 you are welcome! Will get that done soon. I will try to fetch from your branch, so most of the commits remain under your name :-)

**Comment by henriquev16** [comment]
I really apreciate that @onebree thank you! Next time I will try to make pull request each time I change something!

Cheers \o/

**Comment by onebree** [comment]
@henriquev16  so here is the deal. The conflict in your PR is that the files you deleted have been edited since you made your commits. Basically, git is saying "If you delete this file in April, then it will break the changes made to it later on." (More complex than that I am sure.. But bear with me)

To make things easier, I am going to copy your changes and commit them as myself, ensuring there is only 1 commit for the pull request.

I will definitely attribute the work to you in my commit message.

When making multiple changes, even deleting files, I suggest using git, rather than Github, as the later stores every save/delete as its own commit.

**Comment by onebree** [comment]
@henriquev16 after looking into the links you added, I am uneasy about recreating your commits as myself.

1. All links are from an aggregator site, where "DOWNLOAD" redirects the user or asks them to save a file.
2. The C link describes no licensing information
3. The first MATLAB link will redirect to an FTP address. Also explains no licensing
4. The third MATLAB link describes the following licensing information (as per gTranslate)

  > Its content can not be changed. It can not be used (in whole or in part) on the sale or promotion of any product or document.

5. The Pascal download link asks the user to save a ZIP file. (A little shady in my opinion.)

If proper research is made, and all licensing is fair, the only viable link would be the second MATLAB book.

I vote to close this pull request, and wait for @henriquev16 to open another if he wishes to do so.

**Comment by henriquev16** [comment]
Ok thanks and sorry for the trouble! Next time I do commits I will use command-line.

**Comment by vhf** [comment]
@onebree Thanks a lot for all this investigative work. I'll close this one for now, and will take care of all recently submitted PRs in the next hours.

**Comment by henriquev16** [comment]
Ok I understand the problems ! 
Sorry I will make another pull request (following the rules) to change the things I want and forget this one. 

Thank you.

**Comment by onebree** [comment]
@vhf  no problem! Even though the links were not in English, I could still tell it was shady. I think there should be a cleanup of any personal links (gdrive, dropbox) and aggregators.. I saw one in the PT books file.

**Comment by vhf** [comment]
You're absolutely right. I don't like these drive/dropbox links either. I'll leave this issue open as a reminder until I find the time and courage to do this cleanup.

**Pull request closed without merging**
