### PR TITLE
Add A Brief Introduction to Neural Networks

### PR DESCRIPTION
**Pull request by natehefner**

### CODE REVIEW

**Comment by vhf** [comment]
Please replace this URL with the one suggested by the author: http://www.dkriesel.com/en/science/neural_networks

This way, the link won't break when the author updates the PDF URL.

**Comment by natehefner** [comment]
Ah, my fault for overlooking that. Fixed!

**Comment by vhf** [comment]
Thank you! One last thing: please remove the PDF mention, now that the link does not point to a PDF file.

**Comment by natehefner** [comment]
Done, thanks!

**Pull request merged**
