### PR TITLE
Added Go By Example in courses

### PR DESCRIPTION
**Pull request by antimatter96**

### CODE REVIEW

**Comment by thebouv** [comment]
@antimatter96 Check out the Travis build failure details. You need to alphabetize what you added. Easy fix and then test will pass I think.

**Comment by antimatter96** [comment]
Will do it by 17:00 UTC

**Comment by antimatter96** [comment]
Please add hacktoberfest label and close

**Comment by thebouv** [comment]
Hacktoberfest label is not required for the event, just so you know.  This repo may or may not be participating directly, but that doesn't matter.  Any PR opened counts for the event.

The PR also doesn't need to close or be merged to count. Just FYI.  I'm sure this repo's maintainers will get around to it when they can.

Related: check out this Hacktoberfest progress checker to see your progress towards the event. Pretty cool!  https://hacktoberfestchecker.herokuapp.com/

**Comment by vhf** [comment]
https://github.com/vhf/free-programming-books/blame/5754b3f0b30ea4c780e10aaf524e98e33e02974d/free-programming-books.md#L1095

**Comment by fredkrudger** [comment]
you do not have PHP OOP books to from zero to advanced. ?

**Pull request closed without merging**
