### PR TITLE
database books

### PR DESCRIPTION
**Pull request by asd-and-Rizzo**

### CODE REVIEW

**Comment by asd-and-Rizzo** [comment]
Cold you please share comment why pull was rejected?

**Comment by vhf** [comment]
Sure. I don't think these books are actually free.

**Comment by eshellman** [comment]
The first two books by Hugh Darwen are posted on Hugh Darwen's website. The third, published by O'Reilly, is available from O'Reilly with anything filled into the form.

**Comment by asd-and-Rizzo** [comment]
```
Dzmitry Lahoda
10 Apr (13 days ago)
to hughdarwen 
Hi,

What are licenses of these? Please add it to download page.

http://www.thethirdmanifesto.com/   "Documents and Books "

Database Explorations by C.J. Date and Hugh Darwen

Databases, Types, and The Relational Model: The Third Manifesto by C.J. Date and Hugh Darwen

Also free is this one, from O'Reilly:
What is Database Design, Anyway? a free Ebook by C.J. Date (2015). 

Thanks
```
```
Hugh Darwen
15:10 (19 hours ago)
to me 

The downloads available at www.thethirdmanifesto.com are unconditionally free for anybody to use.  Isn't that clear enough?  
If not, what do you suggest I add?  Of course we expect our copyrights to be honoured.

Regards,

Hugh Darwen
```

**Comment by vhf** [comment]
Thanks a lot to you two! I'll reopen and merge this. Better safe than sorry. :)

**Pull request merged**
