### PR TITLE
add link for content about python

### PR DESCRIPTION
**Pull request by gutierri**
language: pt-br

### CODE REVIEW

**Comment by vhf** [comment]
Thanks! Could you please order this link alphabetically?

**Comment by gutierri** [comment]
Fixes?

**Comment by EmreDan** [comment]
Still checking it out
17 Kas 2015 03:15 tarihinde "Gutierri Barboza" <notifications@github.com>
yazdı:

**Comment by vhf** [comment]
Yeah fixed, but conflicts. I'll merge this when I have time to solve the conflicts.

**Pull request merged**
