### PR TITLE
Add Css, HTML and Javascript with various options

### PR DESCRIPTION
**Pull request by GesuitaVolante**
All in Italian

### CODE REVIEW

**Comment by GesuitaVolante** [comment]
I Don't know why The checks have failed

**Comment by eshellman** [comment]
Click on "Details" in the travis report - you need to alphabetize lines and clean up whitespace

**Comment by GesuitaVolante** [comment]
Can you help me? I don't know how to fix
There is a way to fix this, without commit 19023801923 times?

**Comment by eshellman** [comment]
almost there- canoro before guida

git squash or just start from scratch

**Comment by GesuitaVolante** [comment]
Ok, all ok, thank you

**Comment by vhf** [comment]
Thanks!

**Pull request merged**
