### PR TITLE
Add learn:query - Learn JavaScript Fundamentals

### PR DESCRIPTION
**Pull request by michellejanosi**
A free course to learn JavaScript fundamentals by building your own jQuery equivalent library.

### CODE REVIEW

**Comment by kataras** [comment]
@michellejanosi Could you, please, remove the trailing slash from the link?

Replace: 
```
* [learn:query](https://learnquery.infinum.co/)
```
with
 ```
* [learn:query](https://learnquery.infinum.co)
```

**Comment by michellejanosi** [comment]
Apologize for the error. I corrected the link. Thanks!

**Comment by kataras** [comment]
No worries, I'm not an official repository's  maintainer, I just saw that and wanted to give a small help :)

**Comment by vhf** [comment]
Thanks!

**Pull request merged**
