### PR TITLE
Update free-programming-books-pl.md

### PR DESCRIPTION
**Pull request by mbronek7**

### CODE REVIEW

**Comment by vhf** [comment]
Thanks! Where can I find the table of content of this book?

**Comment by mbronek7** [comment]
It contains the full tutorial about HTML langugage and also CSS

**Comment by vhf** [comment]
Could you point me to the table of contents?

**Comment by mbronek7** [comment]
http://www.kurshtml.edu.pl/html/html5.html
http://www.kurshtml.edu.pl/temat.php?q=CSS3

**Comment by vhf** [comment]
Thanks!

**Pull request merged**
