### PR TITLE
Added new Go resources

### PR DESCRIPTION
**Pull request by Jetlum**

### CODE REVIEW

**Comment by Jetlum** [comment]
Ordered the new resources into alphabetical order

**Comment by vhf** [comment]
Hey @Jetlum , blog posts and tutorials are not really books. Thanks anyway!

**Comment by Jetlum** [comment]
Yeah,but you added Go by example and I thought except books we're adding
and tutorials and blog posts

**Comment by vhf** [comment]
To me, Go by example is closer to a book. It consists of snippets thoroughly explained. It's neither a blog post nor a tutorial. I don't have extremely strict rules, but I'm not sure rather short blog posts tutorials helping to create a specific thing don't really qualify here.

**Comment by Jetlum** [comment]
Okay thank you for the answer and from now on will add only books.

**Pull request closed without merging**
