### PR TITLE
First commit. Added R in Action, Hands-On Programming with R and Stat…

### PR DESCRIPTION
**Pull request by navdeep-G**
… Computing in C++ & R

### CODE REVIEW

**Comment by navdeep-G** [comment]
Hi, any reason for the Travis CI build failres? I feel I have matched the formats with the other books links, but maybe I am missing something? Any input would help.

Thanks

**Comment by vhf** [comment]
Hey, sorry about that, travis fails because the linter fails, and the linter fails because the markdown parser it's depending on just changed name. I see you deleted your branch, but do you still want me to merge your changes?

**Comment by navdeep-G** [comment]
Hi,

I see. And yes, if you can that would be great. I think the books I added are quite interesting.

**Comment by vhf** [comment]
I'm sure they are! Thanks for contributing. I just fixed the linter, it should work again from now on!

**Comment by navdeep-G** [comment]
No problem. Do I need to reopen the pull request?

**Comment by vhf** [comment]
If you can, that could be really helpful! :)

**Comment by navdeep-G** [comment]
Cool. Should be there now.

**Pull request closed without merging**
