### PR TITLE
Added livecode english book and italian guide

### PR DESCRIPTION
**Pull request by angerangel**

### CODE REVIEW

**Comment by vhf** [comment]
Thanks! Could you please remove the spaces between `]` and `(`?

**Comment by angerangel** [comment]
Wow, now it's all ok.

**Comment by vhf** [comment]
Yep. And it's not so magical, it's all described in the `CONTRIBUTING.md` shown when you open a PR. ;)

Could you please squash these before I merge?

**Comment by angerangel** [comment]
What do you mean for **squash**?

**Comment by vhf** [comment]
You got 6 commits here. "Merging" them into one single commit is known as "squashing commits".

Here's one way to do it:

1. In your git repo, do `git rebase -i HEAD~6` (because we would like to rebase 6 commits starting at the latest one, which is the current HEAD)
2. It will open an editor. Each line starting with `pick` describes a commit. On the first line, you will see the first commit of this PR, this is the commit we would like to keep, so we will not modify this line. For all the following lines, replace `pick` with `fixup`.
3. Close the editor. Git will start rewriting history.
4. `git push --force`

:)

**Comment by angerangel** [comment]
Sorry, but I use git only on the github website.
How can I do with the website?

**Comment by vhf** [comment]
You cannot do it from the website. I'll do it for you before merging, no worries.

**Comment by angerangel** [comment]
Thank you!

**Pull request merged**
