### PR TITLE
Learning of gulp added in pt-br

### PR DESCRIPTION
**Pull request by gabrielgomesferraz**
Added more one option of learning of one automator of tasks in pt-br

### CODE REVIEW

**Comment by vhf** [comment]
Thanks! Could you please also add a "menu" item for this new category near the top of the file?

**Comment by gabrielgomesferraz** [comment]
Added, please make sure it is correct :smile:

**Comment by vhf** [comment]
Thanks, that's perfect.

**Comment by gabrielgomesferraz** [comment]
Thanks, I will try to always be contributing to the repository. :smiley:

**Pull request merged**
