### PR TITLE
Added WeCodeSign Podcast

### PR DESCRIPTION
**Pull request by IgnaciodeNuevo**
(Spanish Podcast about Front-end, Web Development and UX)

### CODE REVIEW

**Comment by shang-vikas** [comment]
Can I add torrent link of a paid book??.

**Comment by eshellman** [comment]
@IgnaciodeNuevo travis wants you to remove the trailing slash.

@shang-vikas No.

**Comment by IgnaciodeNuevo** [comment]
Done!

**Comment by vhf** [comment]
Thanks !

**Pull request merged**
