### PR TITLE
Add Gulp to free tutorials

### PR DESCRIPTION
**Pull request by onebree**
If needed, I will move to free courses.

### CODE REVIEW

**Comment by vhf** [comment]
Hey, thanks for this link! It's not really an interactive tutorial in my opinion, it's rather a video tutorial or screencast.

**Comment by onebree** [comment]
Will do. Which would you rather? I was in a hurry, so placed in in tutorials because that is what the title says.

On a side note, why does @huhi23 appear as a participant of any/all notifications for this repo? I do not see them on the participants block of this pull request...

**Comment by vhf** [comment]
I think screencast is the best fit.

As for @huhi23, it seems this account has been deleted. Since this repo is somewhat popular on github, it is of interest for spammers. We had trouble with spammers replying to every notifications in the past, but it got better lately. My guess is that @huhi23 was one of them, messed up with this repo, quickly triggered github's spam detector and got their account deleted. :)

**Comment by onebree** [comment]
@vhf I removed the previous commit and created a new one today. I found it difficult to rebase properly without conflicts from recent PR merges.

I also edited the formatting on the screen casts document to match that of the books file.

**Comment by vhf** [comment]
That's great, many thanks!

**Comment by Cleysonlb** [comment]
Hello good afternoon everyone, I wonder who manages the pull requests of free programming books pt-BR, some updated lists but nobody so far accepted the PR

**Comment by vhf** [comment]
Hi @Cleysonlb, that would be me. I'm doing my best to review and merge PRs in a timely fashion, but it can still take me up to a week to do so, so please bear with me. :)

If you think a PR has been wrongfully rejected or if you have the feeling I might have missed it, please ping me (@vhf) there.

**Comment by Cleysonlb** [comment]
I'm Sorry!! I did not know that managed alone haha
I will mark you in PR and wait patiently :)

**Pull request merged**
