### PR TITLE
Added Linux category, and a python book in Korean

### PR DESCRIPTION
**Pull request by BayMinimum**
Added category for linux books
Added a book for linux server mgmt(리눅스 서버를 다루는 기술), a go book for beginner(Go언어 철저 입문), and a python book for beginner (모두의 파이썬) in Korean

### CODE REVIEW

**Comment by kataras** [comment]
@BayMinimum Could you, please, check the alphabetical ordering and put two blank lines between last section and next heading?

**Comment by BayMinimum** [comment]
Oops! Fixed it!

**Comment by kataras** [comment]
Nice!!

**Comment by kataras** [comment]
Nice !! ( I am not any official person of this repository but I just saw the errors and decided to give a help*)

**Comment by vhf** [comment]
Thanks!

**Pull request merged**
