### PR TITLE
Add Using Zend Framework 3 book to PHP section

### PR DESCRIPTION
**Pull request by olegkrivtsov**
Hi, another free book about PHP/Zend Framework 3 to be added to your list

### CODE REVIEW

**Comment by eshellman** [comment]
Nice resource, but the entries need to be in alphabetical order to satisfy Travis CI.

**Comment by eshellman** [comment]
Looks like travis ci wants 2 spaces, not one, after a section

**Comment by olegkrivtsov** [comment]
Checks pass now.

**Comment by vhf** [comment]
Thanks!

**Pull request merged**
