### PR TITLE
Update free-courses-en.md

### PR DESCRIPTION
**Pull request by iammehrabalam**
Added python and flask courses

### CODE REVIEW

**Comment by iammehrabalam** [comment]
Added python and flask courses

**Comment by vhf** [comment]
Thanks! Could you please reorder

```diff
+* [Learn to program in Python](https://www.codecademy.com/learn/python)
```

in alphabetical order?

**Comment by iammehrabalam** [comment]
done alphabetical order

**Comment by vhf** [comment]
Thanks!

**Pull request merged**
