### PR TITLE
推荐一个PHP文章

### PR DESCRIPTION
**Pull request by xbowen94**

### CODE REVIEW

**Comment by vhf** [comment]
Thanks! Could you please remove the blank line you added, sort the new entry alphabetically and squash?

**Comment by xbowen94** [comment]
sorry for that
I update again

**Comment by xbowen94** [comment]
I dont know why it is still failed

**Comment by vhf** [comment]
Click the :x: icon, read the log, fix the alphabetical ordering. ;)

**Comment by xbowen94** [comment]
it's ok this time, you can check if it suits fine:)

**Comment by vhf** [comment]
Perfect :+1: ! Please squash all these commits and we're good to go.

**Comment by xbowen94** [comment]
I'm sorry but I don't understand well, how to squash all commits?

**Comment by vhf** [comment]
You have 9 commits for a single line of content. Merging these 9 commits into a single commit is known as squashing. Here is how you could do this: https://github.com/vhf/free-programming-books/wiki/Squashing

**Comment by xbowen94** [comment]
sorry but it doesn't work:( 
shall we do like this: you close this pull request and i will create a new pull request and we can finish it in 1 time?

**Comment by vhf** [comment]
Ok.

**Comment by xbowen94** [comment]
i create a new pr named <add a new blog for php>

**Pull request closed without merging**
