### PR TITLE
Added AngularJs and javascript category adjusted in pt-br

### PR DESCRIPTION
**Pull request by gabrielgomesferraz**
I added the category angularjs and think better left javascript only what's pure javascript and when it involves node, jquery and other api divide the category is thus better understanding, even if all are javascript.

### CODE REVIEW

**Comment by onebree** [comment]
Your sources needed to be alphabetized within each category.

**Comment by vhf** [comment]
Thank you for this proposition.

I don't really like the idea of mixing frameworks/libraries with languages. It's not a matter of putting them in the same file, rather a matter of not putting them at the same hierarchical level in the index/in the file.

In `free-programming-books.md` we used two approaches. For some languages (e.g. Java), we filed the frameworks/libraries as sub-level titles, both in the content and in the index. For JS, we created a separate file.

What would think of the idea of creating a file named `javascript-frameworks-resources-pt_BR.md` on the same model as `javascript-frameworks-resources.md`, and make a link in the JavaScript category of `free-programming-books-pt_BR.md` pointing to that file?

I think this would be the most consistent way of doing things. I would be happy to discuss this idea here with anyone interested!

**Comment by gabrielgomesferraz** [comment]
Great idea, I would be willing to do it quietly.

**Comment by gabrielgomesferraz** [comment]
Ready, the changes were carried out, please check if everything is okay.

**Comment by vhf** [comment]
Thanks!

**Pull request merged**
