### PR TITLE
Add arabic language books

### PR DESCRIPTION
**Pull request by Tuhamii**
hey @vhf ! 

Great List, I searched the pull requests for Arabic pull request but couldn't find, therefore I made this one. Feel free to check it out and lemme know if there are any errors/syntax.

Cheers ✌️

### CODE REVIEW

**Comment by Tuhamii** [comment]
Found a typo.

**Comment by Tuhamii** [comment]
Fixed alphabetical order.

**Comment by Tuhamii** [comment]
fixed more alphabetical order

**Comment by Tuhamii** [comment]
fixed alphabetical order and blank space

**Comment by Tuhamii** [comment]
I will be adding more resources and books on a daily bases ✌️

**Comment by Tuhamii** [comment]
Adding more open source books soon ✌️

**Comment by vhf** [comment]
Thanks @Tuhamii . Can you confirm that all these books are indeed free?

**Comment by Tuhamii** [comment]
Absolutely I can confirm @vhf . Is there a standard that you want me to follow ?

1. The index pages of the books tells about the author and the license (creative common).
2. http://librebooks.org/ is a free website that distribute free books written by authors (for free)
3. http://blog.algorithmers.com/git/ has two books one is not free in which has to be bought the other is free and downloadable from the author website. (The page is translated to english if you want to check)
4. http://www.ev-center.com/uploads/2/1/2/6/21261678/scratch.pdf - They have books that aren't free and free. I just included the free ones from there Website.

If there is any other way, let me know. I do try to include free / open source books only.

**Comment by Tuhamii** [comment]
hey @vhf 

I hope there is no problems with the pull request ? I was wondering if you can merge it anytime soon

Thanks 🙏

**Comment by vhf** [comment]
Ah sure, sorry about that. I'll merge this right now, I'll take care of the other PRs during the week. :)

**Pull request merged**
