### PR TITLE
Added frameworks PHP - Laravel and CakePHP

### PR DESCRIPTION
**Pull request by gabrielgomesferraz**

### CODE REVIEW

**Comment by vhf** [comment]
Thanks! Your fork is 553 commits behind this repo, could you please redo your PR on top of the current master, to avoid merge conflicts?

**Comment by gabrielgomesferraz** [comment]
@vhf Could you help me with this error?
I'm not managing to solve!

**Comment by gabrielgomesferraz** [comment]
Finally, passed by travis CI :smile:

**Comment by vhf** [comment]
👍 Congrats! I'll check it shortly, thanks in advance!

**Comment by gabrielgomesferraz** [comment]
Thanks :smiley:

**Pull request merged**
